# Generated by Django 6.0 on 2025-12-17 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempricesnapshot',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itempricesnapshot',
            name='best_buy_realm',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='buy_snapshots', to='market.connectedrealm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itempricesnapshot',
            name='best_sell_realm',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='sell_snapshots', to='market.connectedrealm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itempricesnapshot',
            name='profit',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
