# Generated by Django 6.0 on 2025-12-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_itempricesnapshot_buy_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionUpdateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_realms', models.IntegerField(default=0)),
                ('current_realm', models.CharField(blank=True, max_length=100)),
                ('processed_realms', models.IntegerField(default=0)),
                ('is_running', models.BooleanField(default=False)),
            ],
        ),
    ]
