# Generated by Django 6.0 on 2025-12-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_trackeditem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='item',
            name='blizzard_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
