# Generated by Django 6.0 on 2025-12-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_item_options_item_blizzard_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='item_icons/'),
        ),
    ]
