# Generated by Django 6.0 on 2025-12-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_item_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackeditem',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
