# Generated by Django 6.0 on 2025-12-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_item_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackeditem',
            name='added_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackeditem',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
