# Generated by Django 6.0 on 2025-12-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_trackeditem_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('max_realms_to_scan', models.IntegerField(default=0, help_text='0 = todos los reinos, N = número máximo de reinos a escanear')),
                ('primary_realms', models.TextField(default='["Stormrage", "Area 52", "Moon Guard", "Ragnaros", "Dalaran", "Zul\'jin", "Proudmoore"]', help_text='Lista JSON de reinos principales para arbitraje')),
                ('dev_mode', models.BooleanField(default=True, help_text='Modo desarrollo (limitar reinos a 10 para pruebas rápidas)')),
                ('region', models.CharField(default='us', max_length=10)),
                ('locale', models.CharField(default='en_US', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Usuario',
                'verbose_name_plural': 'Configuraciones del Usuario',
            },
        ),
        migrations.AddField(
            model_name='auctionupdatestatus',
            name='config_info',
            field=models.TextField(blank=True, help_text='Información de configuración usada en el escaneo'),
        ),
    ]
