# Generated by Django 6.0 on 2025-12-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_userconfig_auctionupdatestatus_config_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userconfig',
            options={'verbose_name': 'User Configuration', 'verbose_name_plural': 'User Configurations'},
        ),
        migrations.RemoveField(
            model_name='userconfig',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='userconfig',
            name='max_realms_to_scan',
        ),
        migrations.RemoveField(
            model_name='userconfig',
            name='primary_realms',
        ),
        migrations.AddField(
            model_name='userconfig',
            name='realms_to_scan',
            field=models.TextField(default='["Stormrage", "Area 52", "Moon Guard", "Ragnaros", "Dalaran", "Zul\'jin", "Proudmoore"]', help_text='JSON list of realms to scan for arbitrage'),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='dev_mode',
            field=models.BooleanField(default=True, help_text='Development mode (limit realms to 10 for quick tests)'),
        ),
    ]
