# Generated by Django 6.0 on 2025-12-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_alter_userconfig_options_remove_userconfig_locale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='max_realms_to_scan',
            field=models.IntegerField(default=0, help_text='0 = all realms, N = maximum number of realms to scan'),
        ),
    ]
