# Generated by Django 6.0 on 2025-12-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_userconfig_max_realms_to_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempricesnapshot',
            name='top_sell_realms',
            field=models.TextField(blank=True, default='[]', help_text='JSON con top 5 reinos para vender: [{realm, price, profit}, ...]'),
        ),
    ]
